# Generated by Django 4.2.6 on 2024-02-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0003_alter_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CAPTAIN', 'Captian'), ('CLIENT', 'Client'), ('ADMIN', 'Admin')], default='CLIENT', max_length=16),
        ),
    ]
