# Generated by Django 4.2.6 on 2024-02-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0004_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
