# Generated by Django 4.2.6 on 2024-02-24 16:39

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0006_captain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('end', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('price', models.CharField(max_length=256)),
                ('distance', models.CharField(max_length=256)),
                ('captain_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sts.captain')),
                ('client_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
