# Generated by Django 4.2.6 on 2024-02-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0007_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='captain',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
