# Generated by Django 4.2.6 on 2024-02-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0008_captain_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
